server:
  port: 8762
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka,http://${eureka.instance.hostname}:8763/eureka
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false