server:
  port: 10887
spring:
  application:
    name: provider-ribbon-my-loadbalance
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true