server:
  port: 10882
spring:
  application:
    name: provider-ribbon-hello
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true