server:
  port: 8762
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    metadata-map.zone: zone2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      zone1: http://localhost:8761/eureka/
      zone2: http://localhost:8762/eureka/
    region: region-east
    availability-zones:
      region-east: zone1,zone2
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
    remote-region-urls-with-name:
      region-west: http://localhost:8763/eureka