server:
  port: 8764
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    metadata-map.zone: zone4
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      zone3: http://localhost:8763/eureka/
      zone4: http://localhost:8764/eureka/
    region: region-west
    availability-zones:
      region-west: zone3,zone4
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
    remote-region-urls-with-name:
      region-east: http://localhost:8761/eureka