spring:
  rabbitmq:
    addresses: 129.204.35.106:5672
    username: wjj
    password: wzzst310
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true      # Confirm确认消息  消息返回
    publisher-returns: true       # Return消息机制   没有打到队列的消息返回
    template:
      mandatory: true             # 不可达消息经过处理而不是直接丢弃



