server:
  port: 10001
spring:
  application:
    name: zuul-eureka-multizone
eureka:
  instance:
    metadata-map.zone: zone1
  client:
    register-with-eureka: true
    fetch-registry: true
    region: region-east
    service-url:
      zone1: http://localhost:8761/eureka/
      zone2: http://localhost:8762/eureka/
    availability-zones:
      region-east: zone1,zone2

