server:
  port: 8023
spring:
  application:
    name: bb-provider-feign-dynamictarget
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true