server:
  port: 8013
spring:
  application:
    name: consumer-feign-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true  # 设置为true hystix才会生效走Fallback方法