server:
  port: 8012
spring:
  application:
    name: consumer-feign-file
  servlet:
    multipart:
      max-file-size: 20GB
      max-request-size: 20GB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/