server:
  port: 8011
spring:
  application:
    name: provider-feign-file
  servlet:
    multipart:
      max-file-size: 20GB
      max-request-size: 20GB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

